Docker legacy
htr-tech/zphisher pull request #220
Opened 2021-04-22 12:55 UTC by tlt535

1. git clone https://github.com/htr-tech/zphisher
2.cd zphisher
3. ./zphisher.sh

2021-05-08 22:42 UTC, Ehsan9574 commented
apt upgrade

2021-06-17 19:36 UTC, Hackerkuttappan requested changes

2021-06-17 19:36 UTC, Hackerkuttappan commented on Docker/README.md
> +![dockercompose](https://img.shields.io/badge/Docker_Compose-v1.25.4-orange?style=plastic&logo=docker)
''' suggestion
else if line range.length>1
''''

2021-06-17 19:44 UTC, Hackerkuttappan requested changes
fff

2021-06-17 19:44 UTC, Hackerkuttappan commented on Docker/README.md
> +
fff

2021-07-19 18:36 UTC, closed without merging

2025-11-14 20:26 UTC, maryamjafar3206-byte commented
Hotmail

2025-11-14 20:26 UTC, maryamjafar3206-byte commented
Bybit